# Generated by Django 5.0.3 on 2024-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_item_item_prodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://postimg.cc/zbPwkNmk', max_length=500),
        ),
    ]
