# Generated by Django 5.0.3 on 2024-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://i.postimg.cc/Y0tXM2bT/default-product-image.pngk', max_length=500),
        ),
    ]
