# Generated by Django 5.0.3 on 2024-04-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
