# Generated by Django 5.0.3 on 2024-04-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0007_rename_name_post_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',)},
        ),
    ]
