# Generated by Django 5.0.3 on 2024-04-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
    ]
