# Generated by Django 5.0.3 on 2024-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0009_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('time', 'How much time do you have for skincare routine?'), ('skin_type', 'What is your skin type?')], max_length=100)),
                ('answer', models.CharField(choices=[('persontype', [('a', 'New to Skincare'), ('b', 'Some Skincare Knowledge'), ('c', 'Expert in Skincare')]), ('time', [('a', 'Limited (Three-step routine)'), ('b', 'Some (Five-step routine)'), ('c', 'Plenty (Five-step routine)')]), ('skin_type', [('a', 'Dry'), ('b', 'Oily'), ('c', 'Normal')])], default='a', max_length=1)),
            ],
        ),
    ]
