# Generated by Django 5.0.3 on 2024-04-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0010_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
