# Generated by Django 5.0.3 on 2024-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0011_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('Beginner', 'Beginner'), ('Some Knowledge', 'Some Knowledge'), ('Advanced', 'Advanced')], max_length=20)),
                ('time', models.CharField(choices=[('10-15 minutes', '10 - 15 minutes'), ('20-35 minutes', '20 - 35 minutes'), ('Over 35 minutes', 'Over 35 minutes')], max_length=20)),
                ('skin_type', models.CharField(choices=[('Dry', 'Dry'), ('Normal', 'Normal'), ('Oily', 'Oily')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
