# Generated by Django 5.0.3 on 2024-04-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0014_reply_parent_reply'),
    ]

    operations = [
    ]
